"""Repo-aware helpers: locate and load the real taxonomy, schema, and packs."""
from __future__ import annotations

from pathlib import Path

from . import coverage, packs

REPO = Path(__file__).resolve().parents[2]
COMPLIANCE = REPO / "compliance"
SCHEMA_PATH = COMPLIANCE / "schema" / "framework-pack.schema.json"
TAXONOMY_PATH = COMPLIANCE / "control-keys.yaml"
FRAMEWORKS_DIR = COMPLIANCE / "frameworks"
COVERAGE_PATH = COMPLIANCE / "COVERAGE.md"

_GENERATED_BANNER = "<!-- GENERATED by tools/gen_coverage.py — do not edit by hand. -->"


def load_taxonomy() -> dict:
    return packs.load_yaml(TAXONOMY_PATH)


def load_schema() -> dict:
    return packs.load_json(SCHEMA_PATH)


def load_packs() -> list[dict]:
    return [packs.load_yaml(p) for p in sorted(FRAMEWORKS_DIR.glob("*.yaml"))]


def validate_all() -> dict[str, list[str]]:
    """Validate every pack. Returns {framework: [errors]} (only frameworks with errors)."""
    taxonomy = load_taxonomy()
    schema = load_schema()
    valid_keys = packs.extract_keys(taxonomy)
    out: dict[str, list[str]] = {}
    for pack in load_packs():
        errors = packs.validate_pack(pack, valid_keys, schema)
        if errors:
            out[pack.get("framework", "<unknown>")] = errors
    return out


def coverage_markdown() -> str:
    matrix = coverage.build_matrix(load_taxonomy(), load_packs())
    body = coverage.render_markdown(matrix)
    return f"{_GENERATED_BANNER}\n\n# Throughproof framework coverage\n\n{body}"
